name: Desplegar React Vite en HostGator

on:
  push:
    branches:
      - main # Verifica si tu rama principal se llama main o master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código del repositorio
        uses: actions/checkout@v4 # <-- Actualizado a v4

      - name: 2. Configurar el entorno de Node.js
        uses: actions/setup-node@v4 # <-- Actualizado a v4
        with:
          node-version: 20 # <-- Actualizado para evitar advertencias de GitHub

      - name: 3. Instalar dependencias y Compilar Proyecto
        run: |
          npm install --legacy-peer-deps # Agrega --legacy-peer-deps para evitar problemas de dependencias
          npm run build

      - name: 4. Subir archivos a HostGator vía FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/ 
          server-dir: / # <-- ESTE ES EL CAMBIO CLAVE